#! /bin/sh

MONITOR_1="eDP-1"
# MONITOR_1="HDMI-1"
## MONITOR_2="DP-2"


xsetroot -cursor_name left_ptr &

## $1 == width and $2 == height
ibus-daemon &

~/.config/picom/launch.sh &

~/.config/sxhkd/launch.sh &

~/.config/polybar/launch.sh &


nitrogen --restore &

bspc monitor "$MONITOR_1" -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor "$MONITOR_2" -d 6 7 8 9 10
bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

########## floating windows

bspc rule -a GlobalProtect state=floating sticky 
bspc rule -a PanGPUI state=floating sticky 
bspc rule -a "Microsoft Teams - Preview" state=floating sticky 

## sound control
bspc rule -a Pavucontrol state=floating sticky rectangle=1280x720+250+250 focus=on
bspc rule -a Lxappearance state=floating sticky 

## file manager
bspc rule -a Thunar state=floating rectangle=1280x720+250+250 focus=on ## disk analyzr
bspc rule -a Org.gnome.Nautilus state=floating sticky 

## disk analyzer
bspc rule -a Baobab state=floating sticky


# bspc rule -a Gimp desktop='^8' state=tiled follow=on
# bspc rule -a Brave-browser desktop='^2' state=tiled follow=on
# bspc rule -a Chromium desktop='2'
