#! /bin/sh

MONITOR_1="HDMI-0"
MONITOR_2="DP-2"

pgrep -x sxhkd > /dev/null || sxhkd &


~/.config/polybar/launch.sh &
nitrogen --restore &
# picom --experimental-backends &
picom &


bspc monitor "$MONITOR_1" -d 1 2 3 4 5
bspc monitor "$MONITOR_2" -d 6 7 8 9 10
bspc config border_width         1
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiled follow=on
# bspc rule -a Brave-browser desktop='^2' state=tiled follow=on
bspc rule -a Chromium desktop='2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
